version: '3.4'

services:
  whanode-prd:
    image: whanode-prd
    networks:
      apinetwork:
        ipv4_address: 172.20.1.8
    ports:
      - "3333:3333"
    build:
      context: .
      args:
        MODE: production
      dockerfile: ./Dockerfile
    restart: always

networks:
  apinetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16