version: '3.4'

services:
  whanode-prd:
    image: whanode-hml
    networks:
      apinetwork:
        ipv4_address: 172.22.0.8
    ports:
      - "3333:3333"
    build:
      context: .
      args:
        MODE: release
      dockerfile: ./Dockerfile
    restart: always

networks:
  apinetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16